FROM arm64v8/ubuntu:16.04

COPY . .

RUN apt-get update && \
    apt-get install -y --no-install-recommends python-dev libboost-all-dev libcurl3 && \
    rm -rf /var/lib/apt/lists/* 

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT [ "python", "-u", "./main.py" ]